import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { AuthProvider } from "@/context/AuthProvider";
import { ReduxProvider } from "@/store/Provider";
import { RouteProvider } from '@/context/RouteContext';
import { Pilot } from '@/components/Pilot';
import { WakeWordProvider } from "@/context/WakewordProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ReduxProvider>
          <AuthProvider>
            <RouteProvider>
              {children}
              <Toaster />
              <Pilot />
            </RouteProvider>
          </AuthProvider>
        </ReduxProvider>
        <WakeWordProvider>
          <ReduxProvider>
            <AuthProvider>
                {children}
                <Toaster />
            </AuthProvider>
          </ReduxProvider>
        </WakeWordProvider>
      </body>
    </html>
  );
}